// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Article documents */
interface ArticleDocumentData {
    /**
     * title field in *Article*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: article.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * summary field in *Article*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: article.summary
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    summary: prismicT.KeyTextField;
    /**
     * article_author field in *Article*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: article.article_author[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    article_author: prismicT.GroupField<Simplify<ArticleDocumentDataArticleAuthorItem>>;
    /**
     * article_image field in *Article*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: article.article_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    article_image: prismicT.ImageField<never>;
    /**
     * article_content field in *Article*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: article.article_content
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    article_content: prismicT.RichTextField;
}
/**
 * Item in Article → article_author
 *
 */
export interface ArticleDocumentDataArticleAuthorItem {
    /**
     * name field in *Article → article_author*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: article.article_author[].name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * avatar field in *Article → article_author*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: article.article_author[].avatar
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    avatar: prismicT.ImageField<never>;
    /**
     * role field in *Article → article_author*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: article.article_author[].role
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    role: prismicT.KeyTextField;
}
/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ArticleDocumentData>, "article", Lang>;
/** Content for Blog documents */
interface BlogDocumentData {
    /**
     * articles field in *Blog*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: blog.articles
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    articles: prismicT.RelationField;
    /**
     * featuredPost field in *Blog*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: blog.featuredpost
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    featuredpost: prismicT.RelationField;
}
/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<BlogDocumentData>, "blog", Lang>;
/** Content for Homepage documents */
interface HomepageDocumentData {
    /**
     * hero field in *Homepage*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.hero[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    hero: prismicT.GroupField<Simplify<HomepageDocumentDataHeroItem>>;
    /**
     * product_display field in *Homepage*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.product_display[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    product_display: prismicT.GroupField<Simplify<HomepageDocumentDataProductDisplayItem>>;
    /**
     * testimonials field in *Homepage*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.testimonials[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    testimonials: prismicT.GroupField<Simplify<HomepageDocumentDataTestimonialsItem>>;
}
/**
 * Item in Homepage → hero
 *
 */
export interface HomepageDocumentDataHeroItem {
    /**
     * title field in *Homepage → hero*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.hero[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * paragraph field in *Homepage → hero*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.hero[].paragraph
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    paragraph: prismicT.KeyTextField;
    /**
     * background_image field in *Homepage → hero*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.hero[].background_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    background_image: prismicT.ImageField<never>;
}
/**
 * Item in Homepage → product_display
 *
 */
export interface HomepageDocumentDataProductDisplayItem {
    /**
     * title field in *Homepage → product_display*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.product_display[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * highlighted_word field in *Homepage → product_display*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.product_display[].highlighted_word
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    highlighted_word: prismicT.KeyTextField;
    /**
     * paragraph field in *Homepage → product_display*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.product_display[].paragraph
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    paragraph: prismicT.KeyTextField;
    /**
     * desktop_image field in *Homepage → product_display*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.product_display[].desktop_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    desktop_image: prismicT.ImageField<never>;
    /**
     * link field in *Homepage → product_display*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.product_display[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.RelationField;
    /**
     * highlight_color field in *Homepage → product_display*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.product_display[].highlight_color
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    highlight_color: prismicT.ColorField;
    /**
     * mobile_image field in *Homepage → product_display*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.product_display[].mobile_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    mobile_image: prismicT.ImageField<never>;
    /**
     * offset field in *Homepage → product_display*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.product_display[].offset
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    offset: prismicT.NumberField;
    /**
     * reversed field in *Homepage → product_display*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: homepage.product_display[].reversed
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    reversed: prismicT.BooleanField;
}
/**
 * Item in Homepage → testimonials
 *
 */
export interface HomepageDocumentDataTestimonialsItem {
    /**
     * stars field in *Homepage → testimonials*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.testimonials[].stars
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    stars: prismicT.NumberField;
    /**
     * paragraph field in *Homepage → testimonials*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.testimonials[].paragraph
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    paragraph: prismicT.KeyTextField;
    /**
     * avatar field in *Homepage → testimonials*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.testimonials[].avatar
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    avatar: prismicT.ImageField<never>;
    /**
     * author field in *Homepage → testimonials*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.testimonials[].author
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    author: prismicT.KeyTextField;
    /**
     * role field in *Homepage → testimonials*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.testimonials[].role
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    role: prismicT.KeyTextField;
}
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomepageDocumentData>, "homepage", Lang>;
export type AllDocumentTypes = ArticleDocument | BlogDocument | HomepageDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { ArticleDocumentData, ArticleDocumentDataArticleAuthorItem, ArticleDocument, BlogDocumentData, BlogDocument, HomepageDocumentData, HomepageDocumentDataHeroItem, HomepageDocumentDataProductDisplayItem, HomepageDocumentDataTestimonialsItem, HomepageDocument, AllDocumentTypes };
    }
}
